### ISSUE TITLE
test json for parser error

### ISSUE THREAD

**Issue by lukasa1993** [ivanovych666/intellij-json-sorter-plugin#1]
```json
{
  "a": [],
  "b": {
    "\" breaking test": "\"  hard test",
    "\" and you failed": "sorry"
  }
}
```

inside "" escaping \" breaks parser

**Comment by tozarko-softjourn** [comment]
It works with escaped double quotes, but it looks like doesn't work when they are at the beginning of the string. Thank you for this report. I will try to fix this. Or if you already have the solution then please create a pull request.

**Comment by lukasa1993** [comment]
yea i ended up changing \" to ' so i haven't fixed it actually

**Comment by tozarko-softjourn** [comment]
@lukasa1993 Would you mind to test the fix? You can download the fixed plugin [here](https://drive.google.com/open?id=1vh7R-L0_NXubDXML9SVHLy219t_c7Ia6) and install it manually.

**Comment by lukasa1993** [comment]
> @lukasa1993 Would you mind to test the fix? You can download the fixed plugin [here](https://drive.google.com/open?id=1vh7R-L0_NXubDXML9SVHLy219t_c7Ia6) and install it manually.

works in my use cases 👍

**Comment by tozarko-softjourn** [comment]
So quick. Thank you. I have submitted the updated plugin to JetBrains for moderation.
