### ISSUE TITLE
How to install in IntelliJ?

### ISSUE THREAD

**Issue by CodeEsthete** [ivanovych666/intellij-json-sorter-plugin#2]
This plugin can't be found in official JetBrains plugins list or Browse repositories

**Comment by ivanovych666** [comment]
Are you sure? 
![settings_001](https://user-images.githubusercontent.com/17850417/53864738-eac7a280-3ff5-11e9-992f-556ac8ae2866.png)
![search results - plugins jetbrains - mozilla firefox private browsing _002](https://user-images.githubusercontent.com/17850417/53864741-ed29fc80-3ff5-11e9-8409-ef95d8200e29.png)

**Comment by CodeEsthete** [comment]
Yes, I see it after updated IntelliJ to 2018.3.5. Thanks!
