### ISSUE TITLE
Problem with sort order

### ISSUE THREAD

**Issue by jwfx** [ivanovych666/intellij-json-sorter-plugin#4]
I think there may be a small problem with sorting:

When I sort alphabetically (or actually any of the forward sort options), I get the following result:

````
{
    "Add aaaa": "1",
    "Add bbbb": "2",
    "Add zzzz": "3",
    "Add": "4"
}
````

I believe, at least for proper alphabetical sorting, `"Add"` should be at the top of all strings starting with "Add".
This problem seems to appear in all offered sort options.

https://en.wikipedia.org/wiki/Alphabetical_order

"If a position is reached where one string has no more letters to compare while the other does, then the first (shorter) string is deemed to come first in alphabetical order."

**Comment by ivanovych666** [comment]
Hi, thank you for your request. I think that this should be fixed now. The new plugin version is already uploaded but it should be moderated first. If you wish, you can download and try the new plugin from [here](https://drive.google.com/open?id=1vh7R-L0_NXubDXML9SVHLy219t_c7Ia6) right now.

**Comment by jwfx** [comment]
Thanks for this amazingly fast fix. I already tested the new version and it is working great.

Cheers
