### ISSUE TITLE
Plugin does not sort correct

### ISSUE THREAD

**Issue by mrSOMik** [ivanovych666/intellij-json-sorter-plugin#8]
Good day!
I have json like this one.
[  {    "_id": "AD", ...   },
  {     "_id": "AT", ...   },
  {     "_id": "IT", ...},
  {    "_id": "BE", ...  }, ... ]

And after sorting, nothing is happened.
The "_id=IT" is still above of "_id=BE".
I have tried all sorting modes.

Thanks in advance.

**Comment by ivanovych666** [comment]
Hi, if I correctly understand you then you are trying to sort objects in the array, but this plugin does a different job, it is for sorting keys in objects.

**Comment by mrSOMik** [comment]
Is it possible to add this issue?

**Comment by ivanovych666** [comment]
Reordering array elements have totally different sense then reordering object keys. This is not an issue, the purpose of this tool is different.
